apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-streaming-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nats-streaming-operator
  template:
    metadata:
      labels:
        name: nats-streaming-operator
    spec:
      serviceAccountName: nats-streaming-operator
      containers:
      - name: nats-streaming-operator
        image: synadia/nats-streaming-operator:v0.3.0-v1alpha1
        imagePullPolicy: Always
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
