repositories:
  - name: incubator
    url: https://kubernetes-charts-incubator.storage.googleapis.com

releases:
  # - name: stan-pv
  #   chart: incubator/raw
  #   wait: true
  #   force: true
  #   recreatePods: false
  #   installed: true
  #   values:
  #     - resources:
  #         - apiVersion: storage.k8s.io/v1
  #           kind: StorageClass
  #           metadata:
  #             name: stan-storage
  #           provisioner: kubernetes.io/no-provisioner
  #           volumeBindingMode: WaitForFirstConsumer
  #         - apiVersion: v1
  #           kind: PersistentVolume
  #           metadata:
  #             name: stan-pv
  #             labels:
  #               type: local
  #           spec:
  #             storageClassName: stan-storage
  #             capacity:
  #               storage: 1Gi
  #             accessModes:
  #               - ReadWriteOnce
  #             hostPath:
  #               path: "/data/stan"
  #             persistentVolumeReclaimPolicy: Delete
  #         - apiVersion: v1
  #           kind: PersistentVolumeClaim
  #           metadata:
  #             name: stan-pvc
  #             namespace: swarmhub
  #           spec:
  #             storageClassName: stan-storage
  #             accessModes:
  #               - ReadWriteOnce
  #             resources:
  #               requests:
  #                 storage: 1Gi
  #             volumeName: stan-pv

  - name: nats
    namespace: swarmhub
    # needs:
    #   - stan-pv
    chart: ./charts
