---
- hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Gather ec2 facts
      ec2_instance_facts:
        region: "{{ region }}"
        filters:
          instance-state-name: running
          "tag:Name": "locust-*"
          "tag:Grid": "{{ grid_id }}"
      register: ec2_facts
    - debug:
        var: ec2_facts
        verbosity: 2
    
    - name: Add instances to running Ansible group in memory (not persistent between playbook runs).
      add_host:
        groups: "{{ item.0 | replace('-','.') }}"
        hostname: "{{ item.1 }}"
      with_together:
        - "{{ ec2_facts.instances|map(attribute='tags.Name')|list }}"
        - "{{ ec2_facts.instances|map(attribute='public_ip_address')|list }}"

    - name: Add instances to running Ansible group in memory (not persistent between playbook runs).
      add_host:
        groups: "{{ item.0 | replace('-','.') }}.private"
        hostname: "{{ item.1 }}"
      with_together:
        - "{{ ec2_facts.instances|map(attribute='tags.Name')|list }}"
        - "{{ ec2_facts.instances|map(attribute='private_ip_address')|list }}"

#- hosts: "locust-master, locust-slave"
#  gather_facts: no
#  tasks:
#    - name: Wait for connection
#      wait_for_connection:
#        timeout: 60

- hosts: "locust.master, locust.slave"
  user: centos
  roles:
    - locust-deploy-test
