---
- name: include region specific variables
  include_vars: "{{ region }}.yml"

- name: provision vm
  ec2:
    key_name: locust
    instance_type: "{{ instance_type }}"
    image: "{{ ami }}"
    wait: yes
    group: "{{ security_groups }}"
    region: "{{ region }}"
    instance_tags:
        Name: locust-{{ tag_name }}
        App: locust
        Component: "{{ tag_name }}"
        TTL: "{{ tag_ttl }}"
        Grid: "{{ tag_grid }}"
    exact_count: "{{ instance_count }}"
    count_tag:
        Name: locust-{{ tag_name }}
        Grid: "{{ tag_grid }}"

