---
- name: restart locust master
  systemd:
    name: locust-master
    state: restarted
    daemon_reload: yes
  become: yes

- name: restart locust slave
  systemd:
    name: locust-slave-{{ item }}
    state: restarted
    daemon_reload: yes
  become: yes
  with_sequence: count={{ ansible_processor_vcpus }}
  