---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: natsstreamingclusters.streaming.nats.io
  annotations:
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  group: streaming.nats.io
  names:
    kind: NatsStreamingCluster
    listKind: NatsStreamingClusterList
    plural: natsstreamingclusters
    singular: natsstreamingcluster
    shortNames: ["stanclusters", "stancluster"]
  scope: Namespaced
  version: v1alpha1
